# Generated by Django 6.0.1 on 2026-01-29 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_quantity', models.PositiveIntegerField()),
                ('maalem_net_offer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_offer_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_margin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clientprofile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_quantity', models.PositiveIntegerField()),
                ('platform_margin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maalem_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('pickup_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pickedUp', 'Picked Up'), ('delivered', 'Delivered'), ('cash_collected', 'Cash Collected'), ('maalem_paid', 'Maalem Paid'), ('returned', 'Returned')], default='pickedUp', max_length=20)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='sales.offer')),
            ],
        ),
    ]
