# Generated by Django 6.0.1 on 2026-01-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_managed_by_admin', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=255)),
                ('rating', models.FloatField(default=0.0)),
                ('phoneNumber', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaalemProfile',
            fields=[
                ('id_maalem', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
