# Generated by Django 6.0.1 on 2026-01-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='is_managed_by_admin',
        ),
        migrations.AddField(
            model_name='maalemprofile',
            name='is_managed_by_admin',
            field=models.BooleanField(default=True),
        ),
    ]
