# Generated by Django 6.0.1 on 2026-01-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_clientprofile_is_managed_by_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='rating',
        ),
        migrations.AddField(
            model_name='maalemprofile',
            name='address',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maalemprofile',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
