# Generated by Django 6.0.1 on 2026-02-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_clientprofile_rating_maalemprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='phoneNumber',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
